# Generated by Django 2.1.2 on 2018-11-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('Событийный волонтер', 'Событийный волонтер'), ('Волонтер-донор', 'Волонтер-донор'), ('Волонтер общественной безопасности', 'Волонтер общественной безопасности'), ('Медиа-волонтер', 'Медиа-волонтер'), ('Волонтер помощи страдающим паническими атаками', 'Волонтер помощи страдающим паническими атаками'), ('Волонтеры финансовой помощи', 'Волонтеры финансовой помощи')], max_length=120, verbose_name='Роль')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
